### ISSUE TITLE
add github actions to deploy on github pages

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-site#13]
https://github.com/helaili/jekyll-action
https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by vdias38** [comment]
Could it be [deployed on firebase](https://firebase.google.com/docs/hosting/github-integration) after jekyll build ? see .github/workflows

```yaml
name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEUMOBI_WEBSITES }}'
          projectId: meumobi-websites
```
